---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab2rbac
  namespace: gitlab2rbac

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab2rbac
  namespace: gitlab2rbac
  labels:
    app: gitlab2rbac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab2rbac
  template:
    metadata:
      labels:
        app: gitlab2rbac
    spec:
      serviceAccountName: gitlab2rbac
      securityContext:
        runAsNonRoot: true
        runAsUser:  65534 # nobody
      containers:
      - name: gitlab2rbac
        image: numberly/gitlab2rbac
        envFrom:
        - configMapRef:
            name: gitlab2rbac
